Support function rte_pmd_bnxt_set_all_queues_drop_en - rev_2
stephen-hurd/dpdk pull request #1
Opened 2017-01-18 08:54 UTC by steevenlee

1. Add bd_stall attribute to bnxt_vnic_info, reuse bnxt_hwrm_vnic_cfg() to configure bd_stall
2. From test, it looks that bd_stall doesn't take effect for PF.
3. Plan to introduce HWRM_VNIC_**Q**CFG for VNIC to retrieve VF's vnic info, then issue HWRM_VNIC_CFG  with sufficient information, is this correct direction?

2017-01-18 21:39 UTC, stephen-hurd requested changes
A few issues and questions.

2017-01-18 21:39 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt.h
> +#define BNXT_MAX_VF_NUM		128
I'm not sure this should be a macro since it can very by device.  Also, it doesn't seem to be used anywhere.

2017-01-18 21:39 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_ethdev.c
> +int rte_pmd_bnxt_set_tx_loopback(uint8_t port, uint8_t on)
It appears that this function will either do nothing, or return an error.  I don't see where this actually sets tx loopback.

2017-01-18 21:39 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +	if (!vnic->bd_stall)
This breaks the function if bd_stall is true.  I don't see a reason for these enables bits not to be set when bd_stall is true.

2017-01-18 21:39 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +#define HW_MAX_VNICS 170
Where did this number come from?  If we need to track it, we should be able to store what we used in func_cfg when we set up the VFs.

2017-01-18 21:39 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +	num_vnic_ids = resp->vnic_id_cnt;
This needs to use rte_le_to_cpu_32()

2017-01-18 21:39 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +		vnic.fw_vnic_id = vnic_ids[i];
This needs to use rte_le_to_cpu_32()

2017-01-18 21:39 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +		//rc = bnxt_hwrm_vnic_cfg(bp, &vnic);
Why is this commented out?

2017-01-19 00:20 UTC, steevenlee commented on drivers/net/bnxt/bnxt_ethdev.c
> +int rte_pmd_bnxt_set_tx_loopback(uint8_t port, uint8_t on)
VFd need this function to enable/disable loopback mode and it looks that loopback switch not implemented in HWRM.

2017-01-19 00:39 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +	if (!vnic->bd_stall)
Agree!
BTW, from PF test, even comment out this code, traffic still pass PF when bd_stall=1.

2017-01-19 00:40 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +		//rc = bnxt_hwrm_vnic_cfg(bp, &vnic);
I'll complete this if the direction is correct, in other words, introduce hwrm_vnic_qcfg message, read vnic info and update by reusing bnxt_hwrm_vnic_cfg().

2017-01-19 00:41 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.h
> +			   uint8_t on);
To be removed, not used anymore

2017-01-31 00:53 UTC, closed without merging